github:
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
  - https://paypal.me/gabrijelbaban
  - https://revolut.me/glcvr6
  - https://pay.genome.eu/pay?p=dT0xMDUxMDk3ODAwMDc2NDc1NjY0JnQ9MTc5MTQ2MzAzNyZuPUdBQlJJSkVMJTIwQkFCQU4maT1MVDQ4MzExMDAyNzE0NjM2NDUxMyZiPU1OTkVMVDIxWFhYJmM9RVVS
