const fs=require('fs');
const path=require('path');
const s=fs.readFileSync(path.join(__dirname,'..','server','cpanel-mcp.js'),'utf8');
function assert(ok,msg){if(!ok)throw new Error(msg);}
assert(s.includes("async function api2FileOp(c,op,sourcefiles)"),'remote delete API2 helper missing');
assert(s.includes("cpanel_jsonapi_apiversion','2'"),'API2 version missing');
assert(s.includes("async function withOperationLock(c,operation,fn)"),'operation lock helper missing');
assert(s.includes("async function atomicJsonWrite(file,value)"),'atomic JSON writer missing');
assert(s.includes("async function withFileLock(lockPath,operation,fn)"),'shared file lock helper missing');
assert(s.includes("lockId:crypto.randomUUID()"),'lock ownership token missing');
assert(s.includes("current.lockId===owner.lockId"),'lock release must verify ownership before unlinking');
assert(s.includes("async function withProtectionStateLock(fn)"),'protection state lock missing');
assert(s.includes("return await withProtectionStateLock(async()=>"),'accepted state mutation must be serialized');
assert(s.includes("await fsp.rename(tmp,file)"),'atomic JSON writer must replace state via rename');
assert(s.includes("Protection state is unreadable or corrupted"),'corrupt protection state must fail closed');
assert(s.includes("async function saveManifest(m){ await atomicJsonWrite(manifestPath(),m); }"),'manifest writes must be atomic');
assert(s.includes("async function saveRemoteMeta(m){ await atomicJsonWrite(remoteMetaPath(),m); }"),'remote baseline writes must be atomic');
assert(s.includes("fss.open(lockPath,'wx')") || s.includes("fsp.open(lockPath,'wx')"),'lock must use exclusive file creation');
assert(s.includes("process.kill(Number(existing.pid),0)"),'lock recovery must verify whether the recorded owner process is still alive');
assert(s.includes("pidError.code==='ESRCH'"),'lock recovery must distinguish a stale dead-process lock from an active lock');
assert(s.includes("lock metadata is invalid"),'invalid lock metadata must fail closed');
assert(s.includes("protectionEnabled(c,'locks')"),'lock protection gate missing');
assert(s.includes("cleanupRetention(backupRoot(),normalizeSettings(c.settings).backupRetention)"),'local backup retention cleanup missing');
assert(s.includes("const backupName=`${path.basename(rel)}.${suffix}.${Date.now()}.${crypto.randomUUID()}.backup`;"),'remote backups must use unique .backup filenames so retention can find every snapshot');
assert(s.includes("async function walk(current)"),'local backup retention must recurse into nested backup directories');
assert(s.includes("files.sort((a,b)=>b.mtime-a.mtime)"),'local backup retention must use modification time rather than filename order');
assert(s.includes("async function cleanupRemoteBackups(c)"),'remote backup retention cleanup missing');
assert(s.includes("api2FileOp(c,'trash',item.path)"),'remote backup retention must use trash operation');
assert(s.includes("withOperationLock(c,'deploy'"),'deploy lock missing');
assert(s.includes("withOperationLock(c,'remote-sync'"),'remote sync lock missing');
assert(s.includes("withOperationLock(c,'workspace-setup'"),'workspace setup lock missing');
assert(s.includes("withOperationLock(c,'local-upload'"),'full local upload lock missing');
assert(s.includes("withOperationLock(c,'download'"),'download lock missing');
assert(s.includes("async function assertSafeLocalPath(target)"),'local filesystem safety helper missing');
assert(s.includes("async function withManifestLock(fn)"),'manifest transaction lock missing');
assert(s.includes("async function updateManifestEntry(rel,value)"),'manifest entry transaction helper missing');
assert(s.includes("async function buildPlan(c)"),'build plan wrapper missing');
assert(s.includes("return await withManifestLock(()=>buildPlanUnlocked(c));"),'build plan must serialize manifest read-modify-write state');
const downloadStart=s.indexOf("if(name==='cpanel_download')");
const downloadEnd=s.indexOf("\n  throw new Error(`Unknown tool:",downloadStart);
const downloadBlock=s.slice(downloadStart,downloadEnd);
assert(downloadStart>=0&&downloadEnd>downloadStart,'download handler boundaries missing');
assert(!downloadBlock.includes("await Promise.all(workers);await saveManifest(manifest)"),'download handler must not perform a stale final manifest save after worker transactions');
assert(s.includes("st.isSymbolicLink()"),'symbolic links must be rejected in deployment paths');
assert(s.includes("AbortSignal.timeout(120000)"),'cPanel API calls must have bounded timeouts');
assert(s.includes("const VERSION = '1.13.6';"),'server version must match the current release');
console.log('Operation safety regression: PASS');
