const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..');
const m=JSON.parse(fs.readFileSync(path.join(root,'.cursor-plugin/plugin.json')));
if(m.version!=='1.13.2') throw Error('manifest version mismatch');
if(m.author?.name!=='Gabrijel Baban') throw Error('author mismatch');
if(m.repository!=='https://github.com/glcvr6/cpanel-hosting-deploy') throw Error('repository mismatch');
for(const f of ['server/cpanel-mcp.js','mcp.json','commands/cpanel-hosting-settings.md','skills/cpanel-settings/SKILL.md']) if(!fs.existsSync(path.join(root,f))) throw Error('missing '+f);
const mcp=fs.readFileSync(path.join(root,'mcp.json'),'utf8');
if(mcp.includes('${workspaceFolder}')) throw Error('mcp.json must not pass unresolved workspaceFolder');
const server=fs.readFileSync(path.join(root,'server/cpanel-mcp.js'),'utf8');
if(!server.includes('WORKSPACE_FOLDER_PATHS')) throw Error('workspace resolver missing WORKSPACE_FOLDER_PATHS support');
cp.execFileSync(process.execPath,['--check',path.join(root,'server/cpanel-mcp.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/exclude-paths.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/remote-sync-baseline.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/protection-overwrite.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/protection-backups.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/transfer-retry.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/operation-safety.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/partial-success-baseline.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/security-boundaries.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/state-recovery.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/connections-store-safety.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/remote-revalidation.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/remote-path-safety.js')],{stdio:'inherit'});
cp.execFileSync(process.execPath,[path.join(root,'tests/local-fs-operation-safety.js')],{stdio:'inherit'});
console.log('cPanel Hosting Deploy 1.13.2 validation: PASS');
